---
name: Checks

on:
  push:
  pull_request:

jobs:
  checks:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}

    # https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/choosing-the-runner-for-a-job#choosing-github-hosted-runners
    strategy:
      matrix:
        include:
          - name: aarch64-linux
            runs-on: ubuntu-24.04-arm
          - name: aarch64-darwin
            runs-on: macos-15
          - name: x86_64-linux
            runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v17

      - name: Flake Check
        run: nix flake check

      - name: Check Formatting
        run: nix fmt -- --ci
