name: Flake CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  nix-check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Check
        run: nix flake check -L --all-systems
